# Generated by Django 3.0.5 on 2021-01-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiretubers', '0002_auto_20210106_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiretubers',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
