# Generated by Django 3.0.5 on 2021-01-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiretubers', '0003_auto_20210106_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiretubers',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
