# Generated by Django 3.0.5 on 2021-01-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiretubers', '0004_auto_20210106_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiretubers',
            name='interested_in',
        ),
        migrations.AlterField(
            model_name='hiretubers',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
