# Generated by Django 3.0.5 on 2020-12-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='photo',
            field=models.ImageField(upload_to='media/slider/%Y/'),
        ),
    ]
