# Generated by Django 3.0.5 on 2020-12-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_auto_20201225_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='url',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
