# Generated by Django 3.0.5 on 2020-12-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_slider_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=25)),
                ('fb_link', models.CharField(max_length=100)),
                ('insta_link', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(upload_to='media/team/%Y/%m/%d/')),
            ],
        ),
    ]
