# Generated by Django 3.0.5 on 2020-12-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='yt_link',
            field=models.CharField(default='https://www.youtube.com', max_length=50),
        ),
    ]
