# Generated by Django 3.0.5 on 2020-12-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0002_auto_20201229_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='camera_type',
            field=models.CharField(choices=[('Nikon', 'Nikon'), ('Canon', 'Canon'), ('Sony', 'Sony'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='category',
            field=models.CharField(choices=[('Coding', 'Coding'), ('Tech review', 'Tech review'), ('Vlogs', 'Vlogs'), ('Comedy', 'Comedy'), ('Gaming', 'Gaming'), ('Cooking', 'Cooking'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='crew',
            field=models.CharField(choices=[('Solo', 'Solo'), ('Small', 'Small'), ('Large', 'Large')], max_length=50),
        ),
    ]
